name: curt
description: Simple wrapper for curl in dart.
version: 0.0.3
repository: https://github.com/edufolly/curt

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  coverage: ^1.6.3
  dart_code_metrics: ^5.7.0
  lints: ^2.0.0
  markdown: ^7.0.1
  test: ^1.24.0
