name: curt
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/edufolly/curt

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
